# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1, 3
# 6: 1, 2, 3, 6
# 10: 1, 2, 5, 10
# 15: 1, 3, 5, 15
# 21: 1, 3, 7, 21
# 28: 1, 2, 4, 7, 14, 28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

chislo = 84497244
x = 0
for i in range(13000, 14000):
    x = 0
    chislo += i
    if chislo % 10 == 0:
        for j in range(1, chislo//2 + 1):
            if chislo % j == 0:
                x += 1
            else:
                continue
        if x > 500:
            print(chislo)
            print(i)
            break
print(chislo)
print(i)
# break into parts 0(0; 0) 100(384; 73920) 200(2015; 2031120) 300(2079;2162160) 200(2639; 3483480) 200(2975; 4426800)
#  200(3024; 4573800) 200(3135; 4915680) 200(3519; 6193440) 200(3744; 7010640) 200(4128; 8526000)
# 200(4128; 8526000) 200(5328; 14200200) 300(5696; 16228800); 300(7488; 28042560) 300(7551; 28516320)
# 300(9791; 47940480)

# unfinished
