# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

x1 = 1
x2 = 2
summa = 0
i = 0

while x2 < 4000000:
    if x2 % 2 == 0:
        summa += x2
    new_x = x1 + x2
    x1 = x2
    x2 = new_x
    i += 1
print(summa)

# result 4613732
